### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ellingtonc** [ellcrev/intelliplan#1]
SOON:

- [ ] Clean up code and document on my website (crevier.io/projects/intelliplan).
- [ ] Setup Production Meilisearch on my GCE server (35.197.31.143).
- [ ] Create sub-domain for intelliplan on crevier.io.
- [ ] Update the project frontend UI components to be uniform and standardized.
- [ ] Change into a PWA and ensure Lighthouse Score is as high as possible.

LATER:

- [ ] Add my GPT scripts and experiment with Semantic Search via GPT Vector Embeddings.
